#   Copyright (c) 2019 AT&T Intellectual Property.
#   Copyright (c) 2019 Nokia.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Modify this section to point to Docker image repository
image:
  #repository: "snapshot.docker.ranco-dev-tools.eastus.cloudapp.azure.com:10001"
  repository: "192.168.0.6:5000"
  
  #repositoryCred:
  #  user: docker
  #  password: docker
  pullPolicy: Always 
  
# This section describes xAppManager
  replicaCount: 1

  # xAppmanager Docker image name and tag
  name: appmgr
  tag: 0.1.5

  #nameOverride: ""
  #fullnameOverride: ""

  containerPort: 8080

service:
  type: NodePort 
  port: 8080
  nodePort: 30218
  name: appmgr-service
  health_alive_check_endpoint: ric/v1/health/alive
  health_ready_check_endpoint: ric/v1/health/ready

# config
# Path referred in appmgr for retrieving configuration details
appconfigpath: /opt/ric/config
appconfig:
  # To be present as files under appconfigpath
  # Use your own environment addresses
  appmgr.yaml: |
    "local":
      # Port on which the appmgr REST services are provided
      "host": ":8080"
    "helm":
      # Remote helm repo URL. UPDATE this as required.
      "repo": "http://192.168.0.6/charts"

      # Repo name referred within the appmgr
      "repo-name": "helm-repo"

      # Tiller service details in the cluster. UPDATE this as required.
      "tiller-service": "tiller-deploy"
      "tiller-namespace": "kube-system"
      "tiller-port": "44134"

      # helm username and password files
      "helm-username-file": "/opt/ric/secret/helm_repo_username"
      "helm-password-file": "/opt/ric/secret/helm_repo_password"
      "retry": 1
    "xapp":
      #Namespace to install xAPPs
      "namespace": "default"
      "tarDir": "/tmp"
      "schema": "descriptors/schema.json"
      "config": "config/config-file.json"
      "tmpConfig": "/tmp/config-file.json"

# To be provided as env variables
appenv:
  NAME: appmgr-env
  #ENV1: "envvalue1"
  #ENV2: "envvalue2"

# secret
# Path referred in appmgr for retrieving helm repo secrets
appsecretpath: /opt/ric/secret

# Secret object with credentials that should be created in K8S cluster. 
# Parameters in this object are currently referred by appmgr to connect to helm repo and these are:
# helm_repo_username
# helm_repo_password
appsecretobject: appmgr-creds

# certificates
# Path referred in appmgr for retrieving helm repo client certificates
appcertpath: /opt/ric/certificates

# configMap object in K8S cluster that holds the client side certificates to connect to helm repo.
# Currently all certificates mounted by this object are copied to /etc/ssl/certs
appcertobject: appmgr-certs

resources: {}
# limits:
#   cpu: 100m
#   memory: 128Mi
# requests:
#   cpu: 100m
#   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

